[project]
name = "cvlab"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.2",
    "notebook>=7.6.3",
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.6",
    "scikit-image>=0.26.0",
    "scikit-learn>=1.9.1",
    "scipy>=1.18.1",
]

[dependency-groups]
dev = [
    "pyqt6>=6.11.0",
]
